library(forecast)
data <- read.csv(file.choose())
data1 <- ts(THERMAX_NS_1_$`Adj Close`, start = c(2006,1), end = c(2017,4), frequency = 4)
summary(data1)
diff_therm <- diff(data1, 12) #YTD change (April-April)
fit_diff_ar <- arima(diff_therm, order = c(1,0,0)) #AR(1) model with PACF lag(1)
fit_diff_arf <- forecast(fit_diff_ar, h=12) #12 is one period (i.e 1 yr)
plot(fit_diff_arf, include = 20)
acf(THERMAX_NS_1_)